app:
  github-token: ${GITHUB_TOKEN}
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  items-on-page: 100
  access-type: sql
  messaging: kafka
  timeout: 1500

retry:
  wait-duration: 500
  exponential: 2.0
  initial-interval-millis: 500
  max-attempts: 3

rate-limiter:
  limit-for-period: 5
  limit-refresh-period: 5
  timeout-duration: 100


circuit-breaker:
  sliding-window-size: 10
  minimum-number-of-calls: 10
  failure-rate-threshold: 50
  wait-duration-in-open-state: 5
  permitted-number-of-calls-in-half-open-state: 2

kafka:
  topics:
    link-updates: linkUpdates

cache:
  ttl: 3

external:
  api:
    github: http://localhost:8089/repos/
    so: https://api.stackexchange.com/2.3/
    bot: http://localhost:8080/api/v1/

spring:
  profiles:
    active: jpa
  application:
    name: Scrapper
  liquibase:
    enabled: false
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:19092
      acks: 1
      # transactional.id: custom-tx-id
    cloud.zookeeper:
      config.enabled: false
      connect-string: localhost:2181

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    backend.academy.scrapper.data.impl.jdbc.impl.chats: DEBUG
    backend.academy.scrapper.data.impl.jdbc.impl.links: DEBUG
    backend.academy.scrapper.data.impl.jdbc.impl.tracking: DEBUG
    backend.academy.scrapper.config: DEBUG

server:
  port: 0

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
